/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutStudiosIndexImport } from './routes/_layout/studios/index'
import { Route as LayoutStudiosCreateImport } from './routes/_layout/studios/create'
import { Route as LayoutStudiosStudioIdIndexImport } from './routes/_layout/studios/$studioId/index'
import { Route as LayoutStudiosStudioIdEditImport } from './routes/_layout/studios/$studioId/edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutStudiosIndexRoute = LayoutStudiosIndexImport.update({
  path: '/studios/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStudiosCreateRoute = LayoutStudiosCreateImport.update({
  path: '/studios/create',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStudiosStudioIdIndexRoute = LayoutStudiosStudioIdIndexImport.update(
  {
    path: '/studios/$studioId/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutStudiosStudioIdEditRoute = LayoutStudiosStudioIdEditImport.update({
  path: '/studios/$studioId/edit',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/studios/create': {
      id: '/_layout/studios/create'
      path: '/studios/create'
      fullPath: '/studios/create'
      preLoaderRoute: typeof LayoutStudiosCreateImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/studios/': {
      id: '/_layout/studios/'
      path: '/studios'
      fullPath: '/studios'
      preLoaderRoute: typeof LayoutStudiosIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/studios/$studioId/edit': {
      id: '/_layout/studios/$studioId/edit'
      path: '/studios/$studioId/edit'
      fullPath: '/studios/$studioId/edit'
      preLoaderRoute: typeof LayoutStudiosStudioIdEditImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/studios/$studioId/': {
      id: '/_layout/studios/$studioId/'
      path: '/studios/$studioId'
      fullPath: '/studios/$studioId'
      preLoaderRoute: typeof LayoutStudiosStudioIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LayoutRoute: LayoutRoute.addChildren({
    LayoutStudiosCreateRoute,
    LayoutStudiosIndexRoute,
    LayoutStudiosStudioIdEditRoute,
    LayoutStudiosStudioIdIndexRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/studios/create",
        "/_layout/studios/",
        "/_layout/studios/$studioId/edit",
        "/_layout/studios/$studioId/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/studios/create": {
      "filePath": "_layout/studios/create.tsx",
      "parent": "/_layout"
    },
    "/_layout/studios/": {
      "filePath": "_layout/studios/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/studios/$studioId/edit": {
      "filePath": "_layout/studios/$studioId/edit.tsx",
      "parent": "/_layout"
    },
    "/_layout/studios/$studioId/": {
      "filePath": "_layout/studios/$studioId/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
